branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - 2015.12
before_install:
  - rvm install ruby-2.2
install:
  - rakudobrew build panda
  - panda installdeps .
  - perl6 configure.pl6
